const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.FileSystem,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Internationalization,
		C3.Plugins.HTMLElement,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsNWjsExport,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsCordovaExport,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Browser.Exps.Language,
		C3.JavaScriptInEvents.Emain_Event1_Act1,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.JavaScriptInEvents.Emain_Event3_Act1,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.JavaScriptInEvents.Emain_Event4_Act3,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Exps.Count,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.HTMLElement.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.Efights_Event5_Act1,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Text.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{load_icon: 0},
	{Text: 0},
	{FileSystem: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{Internationalization: 0},
	{box_main: 0},
	{box: 0},
	{text1: 0},
	{Touch: 0},
	{Mouse: 0},
	{Sprite: 0},
	{Keyboard: 0},
	{logo: 0},
	{ScrollTo: 0},
	{Sprite2: 0},
	{HTMLElement: 0},
	{Fade: 0},
	{Sine: 0},
	{holder: 0},
	{holderText: 0},
	{texto3: 0},
	{Pin: 0},
	{box2: 0},
	{htmlBox: 0},
	{menu2: 0},
	{debugButton: 0},
	{testButton: 0},
	{gText: 0},
	{Audio: 0},
	{phase: 0},
	{HSL: 0},
	{lerpInstance: 0},
	{pause: 0},
	{eachLetterPause: 0},
	{notFinished: 0},
	{text: 0},
	{csvRow: 0},
	{csvColumn: 0},
	{color: 0},
	{size: 0}
];

self.InstanceType = {
	load_icon: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	FileSystem: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Internationalization: class extends self.IInstance {},
	box_main: class extends self.IHTMLElementInstance {},
	box: class extends self.ISpriteInstance {},
	text1: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	holder: class extends self.ISpriteInstance {},
	holderText: class extends self.ITextInstance {},
	texto3: class extends self.ITextInstance {},
	box2: class extends self.ISpriteInstance {},
	htmlBox: class extends self.IHTMLElementInstance {},
	menu2: class extends self.ISpriteInstance {},
	debugButton: class extends self.IHTMLElementInstance {},
	testButton: class extends self.IHTMLElementInstance {},
	gText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}